//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBusBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleMaster
    {
        public int ScheduleId { get; set; }
        public Nullable<int> BusId { get; set; }
        public string Date { get; set; }
        public Nullable<decimal> Fare { get; set; }
        public string EstimatedTime { get; set; }
        public string ArivalTime { get; set; }
        public string DepartureTime { get; set; }
        public Nullable<int> RouteID { get; set; }
        public Nullable<int> BookedSeats { get; set; }
        public Nullable<int> AvailableSeats { get; set; }
    }
}
